server:
  port: 80

spring:
  application:
    name: consul-consumer-order
    ##注册中心地址
  cloud:
    consule:
      host: lcalhost
      port: 8500
      discovery:
        server-name: ${spring.application.name}





