server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
    ##注册中心地址
  cloud:
    consule:
      host: lcalhost
      port: 8500
      discovery:
        server-name: ${spring.application.name}





