server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  datasource:
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: abcd=1234
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,

